# Generated by Django 5.2.6 on 2025-09-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='BlogPost',
        ),
    ]
