# Generated by Django 5.2.6 on 2025-10-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
